config/routes.rb
Rails.application.routes.draw do
  
  # SIGNUP
  get '/signup', to: 'registrations#new'
  post '/signup', to: 'registrations#create'
 
  # USERS
  get '/profile', to:'users#edit_profile', as: 'profile_edit'
  patch '/profile', to:'users#update_profile', as: 'profile_update'
  get '/profile/changepassword', to:'users#edit_password', as: 'password_edit'
  patch '/profile/changepassword', to:'users#update_password', as: 'password_update'
  delete 'profile', to: 'users#delete_user', as: 'users_delete'

  # SIGNIN
  get '/signin', to: 'signin_sessions#new'
  post '/signin', to: 'signin_sessions#create'
  delete '/', to: 'signin_sessions#destroy'

  # PASSWORD RESET
  get '/password/reset', to: 'password_resets#new'
  post '/password/reset', to: 'password_resets#create'
  get '/password/reset/edit', to: 'password_resets#edit'
  patch '/password/reset/edit', to: 'password_resets#update'
  
  # HOME
  root to: 'home#index'
  get '/dashboard', to: 'home#dashboard'
  get 'tasks/new', to:'home#new_task'
  post 'tasks/new', to:'home#create_task'
  get 'dashboard/:journal_id/tasks/:task_id/:complete', to: 'home#mark_complete', as: 'dashboard_tasks_complete'

  # JOURNALS
  get '/journals/new', to: 'journals#new', as: 'journals_new'
  post '/journals/new', to: 'journals#create', as: 'journals_create'
  get '/journals/:id/edit', to: 'journals#edit', as: 'journals_edit'
  patch '/journals/:id/edit', to: 'journals#update', as: 'journals_update'
  delete '/journals/:id', to: 'journals#delete', as: 'journals_delete'

  # TASKS
  get '/journals/:id/tasks', to: 'tasks#index', as: 'journals_tasks'
  get '/journals/:id/tasks/new', to: 'tasks#new', as: 'journals_tasks_new'
  post '/journals/:id/tasks/new', to: 'tasks#create'
  get '/journals/:id/tasks/:task_id/edit', to: 'tasks#edit', as: 'journals_tasks_edit'
  patch '/journals/:id/tasks/:task_id/edit', to: 'tasks#update', as: 'journals_tasks_update'
  delete '/journals/:id/tasks/:task_id', to: 'tasks#delete', as: 'journals_tasks_delete'
  get '/journals/:id/tasks/:task_id/:complete', to: 'tasks#mark_complete', as: 'journals_tasks_complete'
  get '/journal/:id/tasks/:task_id', to: 'tasks#show', as: 'journals_tasks_show'

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :journal
  belongs_to :user
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { minimum: 4 }
  validate :deadline_not_past
  validates :deadline, presence: true
  
  private

  def deadline_not_past
    return if (deadline.nil? or deadline.today?)
 
    if self.new_record?
      return errors.add(:deadline, "is already past") if deadline.past?
    end

    unless self.new_record?
      old_deadline, new_deadline = self.deadline_change

      return if old_deadline.nil?

      return if ((new_deadline == old_deadline) and !new_deadline.past?)

      return errors.add(:deadline, "is already past") if new_deadline.past?
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :redirect_if_not_loggedin
  before_action :get_journal

  def index
    @tasks = @journal.tasks.order("created_at ASC")
  end
  
  def show
    @task = Task.find(params[:task_id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    @task.journal_id = params[:id]
    @task.user_id = Current.user.id
    puts params[:id]
    if @task.save
      redirect_to journals_tasks_path, notice: "Successfully add #{@task.name} task to #{@journal.name} journal"
    else 
      render :new
    end
  end

  def mark_complete
    @task = Task.find(params[:task_id])
    complete = params[:complete] == '1' ? false : true
    @task.update_attribute(:completed, complete)
    redirect_to journals_tasks_path
  end

  def edit
    @task = Task.find(params[:task_id])
    puts params[:task_id]
  end

  def update
    @task = Task.find(params[:task_id])
    if @task.update(task_params)
      redirect_to journals_tasks_path
    else
      render :edit
    end
  end

  def delete
    @task = Task.find(params[:task_id])
    @task.destroy

    redirect_to journals_tasks_path, notice: "Successfully deleted #{@task.name} from #{@journal.name} journal"
  end

  private

  def get_journal
    @journal = Journal.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :deadline)
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<div class="flex justify-center items-center " style='height:90vh; '>
  <div class="w-full max-w-lg shadow-md rounded" style="background-image:linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7))">
    <%= form_with :class => "px-8 pt-6 pb-8 mb-4", model: @task, url: journals_tasks_update_path, method: :patch, locale: true do |f| %>
    <h1 class="mb-5 text-3xl text-yellow-500">Edit Tasks</h1>

    <div class="mb-4">
      <%= f.label :task_title, :class => "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_field :name,  :class => "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'task Title' %>
      <% @task.errors.full_messages_for(:name).each do |message| %>
        <div style="color:red;"><%= message %></div>
      <% end %>
    </div>
    <div class="mb-6">
      <%= f.label :Description, :class => "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_area :description,  :class => "h-44 shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'Description' %>
      <% @task.errors.full_messages_for(:description).each do |message| %>
        <div style="color:red;"><%= message %></div>
      <% end %>
    </div>

    <div class="mb-6">
      <%= f.label :Deadline, :class => "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.date_field  :deadline,  :class => "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'Description' %>
      <% @task.errors.full_messages_for(:deadline).each do |message| %>
        <div style="color:red;"><%= message %></div>
      <% end %>
    </div>
     
    <div class="flex items-center justify-between">
      <%= link_to 'Back', journals_tasks_path, :class => "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"%>
      <%= f.submit "Save", :class => "bg-yellow-600 hover:bg-yellow-400 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer" %>
    </div>
    <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
  <div class="max-w-7xl mx-auto ">
  
    <div class=" container my-12 mx-auto px-4 md:px-12 grid grid-cols-1 sm:grid-cols-1  gap-5" >
      <div class="flex justify-between rounded  text-3xl font-bold py-6 px-4 sm:px-6 lg:px-8 text-white-400 " style="background-image:linear-gradient(rgba(0,0,0,.6),rgba(0,0,0,.6));">
        <h1 class="text-yellow-400 "><%= @journal.name.capitalize%> Journal</h1>
         <div><%= link_to journals_tasks_new_path(@journal.id) do %><button class="fas fa-plus bg-yellow-600 hover:bg-yellow-400 text-sm text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer"> Add Tasks</button>  <% end %></div>
      </div>
    </div>
    
  <% if @tasks.length > 0 %>
          
    <div class="container my-12 mx-auto px-4 md:px-12 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3  xl:grid-cols-3 gap-5">

      <% @tasks.each do |task|%>
        <div class="rounded overflow-hidden shadow-lg " style="background-image:linear-gradient(rgba(0,0,0,.6),rgba(0,0,0,.6));">
          <div class="px-6 py-4">
            <div style="float:right;">
             <%#= raw task_label(task)[:html] %> <%#= link_to "tasks/#{task.id}", method: :delete, data: { confirm: "are you sure? you want to delete #{task.name}" } do %>
            <%= link_to journals_tasks_delete_path(task.journal_id, task.id), method: :delete, data: { confirm: "are you sure?" } do %><button class="ml-3 fas fa-times text-red-700"> </button><% end %>
            <%# end %>
            </div>
            <div style="float:right;">
              <%if task.completed? %>
                <p class="text-green-500"> Completed </p>
              <% else %>

                <% if task.deadline.today? %>
                  <p class="text-yellow-500">Due Today!</p>
                <% elsif task.deadline.past?%>
                  <p class="text-red-500">Overdue!</p>
                <% elsif task.deadline.future?%>
                  <p class="text-blue-500">Pending</p>
                <% end %>

              <% end %>
              
            </div>
            <div class="font-bold text-xl mb-2 text-yellow-400"><%#=task.name%> <%=task.name%></div>
              <p class="text-gray-300 text-base mt-5">
                <%=task.description%>
              </p>
              <br>
              <h1>Deadline <%=task.deadline.strftime("%A %b %e, %Y ")%></h1>
            </div>
              <div class="px-6 pt-4 pb-2 column-button">
              <%= link_to journals_tasks_complete_path(task.journal_id, task.id, task.completed ? '1' : '0') do %>
                <button class="#{task.completed ? fas fa-check : fas fa-times}  inline-block bg-green-300 hover:bg-green-400 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"> 
                  <% if task.completed %>
                  Unmark completed
                  <% else %>
                  Mark completed
                  <% end %>
                </button>
              <% end %>
              <%= link_to journals_tasks_show_path(@journal.id, task.id) do %><button class="fas fa-eye inline-block bg-blue-300 hover:bg-blue-400 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"> View</button><% end %>
              <%= link_to journals_tasks_update_path(@journal.id, task.id) do %><button class="fas fa-edit inline-block bg-yellow-300 hover:bg-yellow-400 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"> Edit</button><% end %>
          </div>
        </div>
      <% end %>

    </div>
    <% else %>

    <div class="container my-12 mx-auto px-4 md:px-12">
      <div class="flex flex-col justify-center direction-column items-center rounded overflow-hidden shadow-lg  p-5 " style=" height:65vh; background-image:linear-gradient(rgba(0,0,0,.6),rgba(0,0,0,.6));">
        <h1 class="text-white">No tasks found for this journal</h1>
        <%= link_to "tasks/new"  do %><i class="mt-5 fas fa-plus  font-bold py-2 px-4 rounded-full text-xl mr-5 bg-yellow-600 hover:bg-yellow-500 text-sm text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer"> Add tasks now</i><% end %>
      </div>
    </div>

  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="flex justify-center items-center " style='height:90vh; '>
  <div class="w-full max-w-lg shadow-md rounded" style="background-image:linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7))">
    <%= form_with :class => "px-8 pt-6 pb-8 mb-4", model: @task, url: journals_tasks_new_path, locale: true do |f| %>
    
    <h1 class="mb-5 text-3xl text-yellow-500">Add Tasks</h1>

    <div class="mb-4">
      <%= f.label :task_title, :class => "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_field :name,  :class => "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'task Title' %>
      <% @task.errors.full_messages_for(:name).each do |message| %>
        <div style="color:red;"><%= message %></div>
      <% end %>
    </div>
    <div class="mb-6">
      <%= f.label :Description, :class => "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_area :description,  :class => "h-44 shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'Description' %>
      <% @task.errors.full_messages_for(:description).each do |message| %>
        <div style="color:red;"><%= message %></div>
      <% end %>
    </div>

    <div class="mb-6">
      <%= f.label :Deadline, :class => "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.date_field  :deadline,  :class => "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'Description' %>
      <% @task.errors.full_messages_for(:deadline).each do |message| %>
        <div style="color:red;"><%= message %></div>
      <% end %>
    </div>
     
    <div class="flex items-center justify-between">
      <%= link_to 'Back', journals_tasks_path, :class => "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"%>
      <%= f.submit "Save", :class => "bg-yellow-600 hover:bg-yellow-400 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer" %>
    </div>
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container my-12 mx-auto text-3xl px-4 md:px-12 show-tasks">
  <div class="flex flex-wrap justify-evenly items-center rounded overflow-hidden shadow-lg  p-5 " style=" height:65vh; background-image:linear-gradient(rgba(0,0,0,.6),rgba(0,0,0,.6));">
    <div class="text-yellow-400 font-bold show-div">
      <h1>Title:</h1>
      <h1>Description:</h1>
      <h1>Deadline:</h1>
      <h1>Status</h1>
    </div>
    <div class="text">
      <h1 class="text-white"><%=@task.name%></h1>
      <h1 class="text-white"><%=@task.description%></h1>
      <h1 class="text-white"><%=@task.deadline.strftime("%A %b %e, %Y ")%></h1>
      <%if @task.completed? %>
        <p class="text-green-500"> Completed </p>
          <% else %>
            <% if @task.deadline.today? %>
              <p class="text-yellow-500 today">Due Today!</p>
            <% elsif @task.deadline.past?%>
              <p class="text-red-500 past ">Overdue!</p>
            <% elsif @task.deadline.future?%>
              <p class="text-blue-500 pending">Pending</p>
            <% end %>
        <% end %>
    </div>
    <div class="column-button">
      <%= link_to journals_tasks_path do %><button class="fas fa-eye inline-block bg-blue-300 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"> See all tasks</button><% end %>
      <%= link_to journals_tasks_edit_path do %><button class="fas fa-edit inline-block bg-yellow-300 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"> Edit</button><% end %>
      <%= link_to journals_tasks_delete_path , method: :delete, data: { confirm: "are you sure? you want to delete #{@task.name}" } do %><button class="fas fa-trash inline-block bg-red-300 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"> Delete</button><% end %>
    </div>
  </div>
</div>