config/routes.rb
Rails.application.routes.draw do
  
  # SIGNUP
  get '/signup', to: 'registrations#new'
  post '/signup', to: 'registrations#create'
 
  # USERS
  get '/profile', to:'users#edit_profile', as: 'profile_edit'
  patch '/profile', to:'users#update_profile', as: 'profile_update'
  get '/profile/changepassword', to:'users#edit_password', as: 'password_edit'
  patch '/profile/changepassword', to:'users#update_password', as: 'password_update'
  delete 'profile', to: 'users#delete_user', as: 'users_delete'

  # SIGNIN
  get '/signin', to: 'signin_sessions#new'
  post '/signin', to: 'signin_sessions#create'
  delete '/', to: 'signin_sessions#destroy'

  # PASSWORD RESET
  get '/password/reset', to: 'password_resets#new'
  post '/password/reset', to: 'password_resets#create'
  get '/password/reset/edit', to: 'password_resets#edit'
  patch '/password/reset/edit', to: 'password_resets#update'
  
  # HOME
  root to: 'home#index'
  get '/dashboard', to: 'home#dashboard'
  get 'tasks/new', to:'home#new_task'
  post 'tasks/new', to:'home#create_task'
  get 'dashboard/:journal_id/tasks/:task_id/:complete', to: 'home#mark_complete', as: 'dashboard_tasks_complete'

  # JOURNALS
  get '/journals/new', to: 'journals#new', as: 'journals_new'
  post '/journals/new', to: 'journals#create', as: 'journals_create'
  get '/journals/:id/edit', to: 'journals#edit', as: 'journals_edit'
  patch '/journals/:id/edit', to: 'journals#update', as: 'journals_update'
  delete '/journals/:id', to: 'journals#delete', as: 'journals_delete'

  # TASKS
  get '/journals/:id/tasks', to: 'tasks#index', as: 'journals_tasks'
  get '/journals/:id/tasks/new', to: 'tasks#new', as: 'journals_tasks_new'
  post '/journals/:id/tasks/new', to: 'tasks#create'
  get '/journals/:id/tasks/:task_id/edit', to: 'tasks#edit', as: 'journals_tasks_edit'
  patch '/journals/:id/tasks/:task_id/edit', to: 'tasks#update', as: 'journals_tasks_update'
  delete '/journals/:id/tasks/:task_id', to: 'tasks#delete', as: 'journals_tasks_delete'
  get '/journals/:id/tasks/:task_id/:complete', to: 'tasks#mark_complete', as: 'journals_tasks_complete'
  get '/journal/:id/tasks/:task_id', to: 'tasks#show', as: 'journals_tasks_show'

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password 
  
  has_many :tasks, dependent: :destroy
  has_many :journals, dependent: :destroy

  validates :username, :email, uniqueness: true
  validates :username, :firstname, :lastname, :email, presence: true
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i, message: "must be a valid email address"}
  validates :password, :confirmation => true,  length: { minimum: 8 }, presence: true, on: :create
  validates :password, :password_confirmation, presence: true, on: :create

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_not_loggedin 

  def edit_profile
  end

  def update_profile
    # Current.user.update_without_password(user_params)
    if Current.user.update(user_params)
      redirect_to dashboard_path, notice: "Successfully updated user"
    else
      puts 'error'
      render :edit_profile
    end
  end

  def edit_password
  end

  def update_password
    my_password = BCrypt::Password.new(Current.user.password_digest)
    if my_password == user_params[:current_password]
      if user_params[:password] == user_params[:password_confirmation]
        if user_params[:password].length >= 8
          Current.user.update({
            password_digest: BCrypt::Password.create(user_params[:password])
          })
          redirect_to root_path, notice: "Successfully change password"
        else
          flash[:length] = "Password is too short (minimum is 8 characters)"
          render :edit_password
        end
      else
        flash[:not_match] = "New Password and Confirm New password does not match"
        render :edit_password
      end
    else
      flash[:invalid] = "Invalid current password"
      render :edit_password
    end
  end

  def delete_user
    Current.user.destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Successfully Deleted User"
  end
  private

  def user_params
    params.require(:user).permit(:username, :firstname, :lastname, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit_password.html.erb
<div class="flex justify-center items-center" style='height:90vh;'>
  <div class="w-full max-w-lg shadow-md rounded " style="background-image:linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7))">
      <%= form_with :class => "px-8 pt-6 pb-8 mb-4", model: Current.user, url: password_update_path, method: :patch, locale: true do |f| %>
      <h1 class="mb-5 text-3xl text-yellow-500">Edit Password</h1>
      <div class="mb-6">
        <%= f.label :Current_Password, :class => "block text-gray-400 text-sm font-bold mb-2" %>
        <%= f.password_field :current_password, :class => "shadow appearance-none border rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'Password', :required => true %>
        <% if flash[:invalid] %>
          <div class="text-red-400 font-bold mt-2 validations"><%= flash[:invalid]%></div>
        <% end %>
      </div>
      <div class="mb-6">
        <%= f.label :New_Password, :class => "block text-gray-400 text-sm font-bold mb-2" %>
        <%= f.password_field :password, :class => "shadow appearance-none border rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'Password', :required => true %>
      </div>
      <div class="mb-4">
        <%= f.label :Confirm_new_Password, :class => "block text-gray-400 text-sm font-bold mb-2" %>
        <%= f.password_field :password_confirmation, :class => "shadow appearance-none border rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'PasswordConfirmation', :required => true %>
        <% if flash[:not_match] %>
          <div class="text-red-400 font-bold mt-2 validations"><%= flash[:not_match]%></div>
           <% elsif flash[:length] %>
          <div class="text-red-400 font-bold mt-2 validations"><%= flash[:length]%></div>
        <% end %>
      </div>
      <br>
      
      <div class="flex items-center justify-between">
        <%= f.submit "Update Changes", :class => "w-full bg-yellow-600 hover:bg-yellow-400 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer" %>
      </div>
        <br>
      <div class="flex items-center justify-between">
        <%= link_to 'Back', profile_edit_path, :class => "text-center w-full bg-white hover:bg-white text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer" %>
      </div>
    
    <% end %>
  </div>
</div>

<script>
	var validation = document.querySelector('.validations')
  console.log(validation)
	if (validation) {
		setTimeout(() => {
			validation.style.display = 'none'
		}, 4000);
	}
</script>

app/views/users/edit_profile.html.erb
<div class="flex justify-center items-center" style='height:90vh;'>
  <div class="w-full max-w-lg shadow-md rounded " style="background-image:linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7))">
      <%= form_with :class => "px-8 pt-6 pb-8 mb-4", model: Current.user, url: profile_update_path, method: :patch, locale: true do |f| %>
      <h1 class="mb-5 text-3xl text-yellow-500">Edit Profile</h1>
      <div class="mb-4">
        <%= f.label :Username, :class => "block text-gray-400 text-sm font-bold mb-2" %>
        <%= f.text_field :username,  :class => "shadow appearance-none border rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'Username', :required => true %>
          <% Current.user.errors.full_messages_for(:username).each do |message| %>
        <div class="text-red-900 font-bold"><%= message %></div>
        <% end %>
      </div>
      <div class="mb-4">
        <%= f.label :Firstname, :class => "block text-gray-400 text-sm font-bold mb-2" %>
        <%= f.text_field :firstname, :class => "shadow appearance-none border rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'Firstname', :required => true %>
        <% Current.user.errors.full_messages_for(:firstname).each do |message| %>
          <div class="text-red-400 font-bold"><%= message %></div>
        <% end %>
      </div>
      <div class="mb-4">
        <%= f.label :Lastname, :class => "block text-gray-400 text-sm font-bold mb-2" %>
        <%= f.text_field :lastname, :class => "shadow appearance-none border rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'Lastname', :required => true %>
        <% Current.user.errors.full_messages_for(:lastname).each do |message| %>
          <div class="text-red-400 font-bold"><%= message %></div>
        <% end %>
      </div>
      <div class="mb-4">
        <%= f.label :Email, :class => "block text-gray-400 text-sm font-bold mb-2" %>
        <%= f.email_field :email, :class => "shadow appearance-none border rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'Email', :required => true , :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}'%>
        <% Current.user.errors.full_messages_for(:email).each do |message| %>
          <div class="text-red-400 font-bold"><%= message %></div>
        <% end %>
      </div>
      <%= link_to users_delete_path, method: :delete, data: { confirm: "are you sure? you want to delete this user #{Current.user.email}? You will never retrieve this again!" } do %><button class="mb-5 text-red-500 hover:text-red-600 p-1 rounded"><i class="fas fa-user-slash "></i> Not happy? Delete User</button><% end %>
      <br>
      <div class="flex items-center justify-between">
        <%= link_to 'Change Password', password_edit_path, :class => "text-center w-full bg-white hover:bg-white text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer" %>
      </div>
      <br>
      <div class="flex items-center justify-between">
        <%= f.submit "Save Changes", :class => "w-full bg-yellow-600 hover:bg-yellow-400 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer" %>
      </div>
      <br>
    
    <% end %>
  </div>
</div>

 <div class="mb-6">
        <%#= f.label :Current_Password, :class => "block text-gray-400 text-sm font-bold mb-2" %>
        <%#= f.password_field :password, :class => "shadow appearance-none border rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'Password', :required => true %>
        <%# Current.user.errors.full_messages_for(:password).each do |message| %>
          <div class="text-red-400 font-bold"><%#= message %></div>
        <%# end %>
      </div>
      <div class="mb-6">
        <%#= f.label :New_Password, :class => "block text-gray-400 text-sm font-bold mb-2" %>
        <%#= f.password_field :password, :class => "shadow appearance-none border rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'Password', :required => true %>
        <%# Current.user.errors.full_messages_for(:password).each do |message| %>
          <div class="text-red-400 font-bold"><%#= message %></div>
        <%#end %>
      </div>
      <div class="mb-4">
        <%#= f.label :Confirm_new_Password, :class => "block text-gray-400 text-sm font-bold mb-2" %>
        <%#= f.password_field :password_confirmation, :class => "shadow appearance-none border rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'PasswordConfirmation', :required => true %>
        <%#Current.user.errors.full_messages_for(:password_confirmation).each do |message| %>
          <div class="text-red-400 font-bold"><%#= message %></div>
        <%# end %>
      </div>