config/routes.rb
Rails.application.routes.draw do
  
  # SIGNUP
  get '/signup', to: 'registrations#new'
  post '/signup', to: 'registrations#create'
 
  # USERS
  get '/profile', to:'users#edit_profile', as: 'profile_edit'
  patch '/profile', to:'users#update_profile', as: 'profile_update'
  get '/profile/changepassword', to:'users#edit_password', as: 'password_edit'
  patch '/profile/changepassword', to:'users#update_password', as: 'password_update'
  delete 'profile', to: 'users#delete_user', as: 'users_delete'

  # SIGNIN
  get '/signin', to: 'signin_sessions#new'
  post '/signin', to: 'signin_sessions#create'
  delete '/', to: 'signin_sessions#destroy'

  # PASSWORD RESET
  get '/password/reset', to: 'password_resets#new'
  post '/password/reset', to: 'password_resets#create'
  get '/password/reset/edit', to: 'password_resets#edit'
  patch '/password/reset/edit', to: 'password_resets#update'
  
  # HOME
  root to: 'home#index'
  get '/dashboard', to: 'home#dashboard'
  get 'tasks/new', to:'home#new_task'
  post 'tasks/new', to:'home#create_task'
  get 'dashboard/:journal_id/tasks/:task_id/:complete', to: 'home#mark_complete', as: 'dashboard_tasks_complete'

  # JOURNALS
  get '/journals/new', to: 'journals#new', as: 'journals_new'
  post '/journals/new', to: 'journals#create', as: 'journals_create'
  get '/journals/:id/edit', to: 'journals#edit', as: 'journals_edit'
  patch '/journals/:id/edit', to: 'journals#update', as: 'journals_update'
  delete '/journals/:id', to: 'journals#delete', as: 'journals_delete'

  # TASKS
  get '/journals/:id/tasks', to: 'tasks#index', as: 'journals_tasks'
  get '/journals/:id/tasks/new', to: 'tasks#new', as: 'journals_tasks_new'
  post '/journals/:id/tasks/new', to: 'tasks#create'
  get '/journals/:id/tasks/:task_id/edit', to: 'tasks#edit', as: 'journals_tasks_edit'
  patch '/journals/:id/tasks/:task_id/edit', to: 'tasks#update', as: 'journals_tasks_update'
  delete '/journals/:id/tasks/:task_id', to: 'tasks#delete', as: 'journals_tasks_delete'
  get '/journals/:id/tasks/:task_id/:complete', to: 'tasks#mark_complete', as: 'journals_tasks_complete'
  get '/journal/:id/tasks/:task_id', to: 'tasks#show', as: 'journals_tasks_show'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :redirect_if_not_loggedin, except: [:index]

  def index
  end

  def dashboard
    @journals = Journal.where(user_id: Current.user.id).order("created_at ASC")
    @tasks = Task.where(user_id: Current.user.id).order("created_at ASC")
    @count_completed = statistics(@journals)
  end

  def mark_complete
    @task = Task.find(params[:task_id])
    complete = params[:complete] == '1' ? false : true
    @task.update_attribute(:completed, complete)
    redirect_to dashboard_path
  end

  def new_task
    @task = Task.new
    if Current.user.journals.length == 0
      flash[:error] = "Please create a journal first"
      redirect_to journals_new_path
    end
  end

  def create_task
    @task = Task.create(create_params_task)
    @task.user_id = Current.user.id
    if @task.save
      redirect_to journals_tasks_path(@task.journal_id), notice: "Successfully add #{@task.name} task"
    else 
      # byebug
      puts 'error'
      render :new_task
    end
  end

  private

  def create_params_task
    params.require(:task).permit(:name, :description, :journal_id, :deadline, :user_id)
  end

  def statistics(journal_array)
    count = { completed: 0, not_completed: 0 }
    journals = Hash.new

    journal_array.each do |journal|
      journal_statistics = { journal_id: journal.id, completed: 0, not_completed: 0 }

      journal.tasks.each do |task|
        if task.completed
          count[:completed] += 1
          journal_statistics[:completed] += 1
        end

      #   unless task.completed
      #     count[:not_completed] += 1
      #     journal_statistics[:not_completed] += 1
      #   end
      end

      journals[journal.id] = journal_statistics
    end

    { count: count, journals: journals }
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/dashboard.html.erb
  <div class="max-w-7xl mx-auto ">
    <div class=" container my-12 mx-auto px-4 md:px-12 grid grid-cols-1 sm:grid-cols-1  gap-5" >
      <div class=" rounded  text-3xl font-bold py-6 px-4 sm:px-6 lg:px-8 text-yellow-400 " style="background-image:linear-gradient(rgba(0,0,0,.6),rgba(0,0,0,.6));">
      <img src="https://icons8.com/animated-icons/set/animated%20gif" class="mb-4" srcset="https://a.slack-edge.com/6c404/marketing/img/homepage/bold-existing-users/waving-hand.gif 1x, https://a.slack-edge.com/6c404/marketing/img/homepage/bold-existing-users/waving-hand@2x.gif 2x" alt="" height="56" width="52" />
        Hello, <%= Current.user.firstname.capitalize%> 
      </div>
    </div>
          
    <div class="container my-12 mx-auto px-4 md:px-12 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3  xl:grid-cols-3 gap-5">

      <% @journals.each do |journal|%>
        <div class="rounded overflow-hidden shadow-lg " style="background-image:linear-gradient(rgba(0,0,0,.6),rgba(0,0,0,.6));">
          <div class="px-6 py-4">
          <%= link_to "journals/#{journal.id}", method: :delete, data: { confirm: "are you sure?" } do %><button class="fas fa-times text-red-700" style="float:right;"> </button><% end %>
        <div class="font-bold text-xl mb-2 text-yellow-400"> <%=journal.name%></div>
            <p class="text-gray-300 text-base mt-5">
              <%=journal.description%>
            </p>
            <h1 class="mt-5"><%#= journal.status === 0 ? "Completed" : "Completed" %></h1>
            <h1 class="text-green-500"><%= @count_completed[:journals][journal.id][:completed]  %> Completed<h1/>
            <h1 class="text-yellow-400"><%= journal.tasks.length > 0 ? journal.tasks.length : 'No'%> tasks</h1>
            <h1 class="mt-5"><%= journal.created_at.strftime("%A %b %e, %Y ") %></h1>
          </div>
            <div class="px-6 pt-4 pb-2 column-button">
         <%= link_to journals_tasks_new_path(journal.id) do %><button class="fas fa-plus inline-block bg-red-200 hover:bg-red-400 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"> Add Tasks</button>  <% end %>
            <%= link_to journals_tasks_path(journal.id) do %><button class="fas fa-eye inline-block bg-blue-200 hover:bg-blue-400 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"> View Journal</button><% end %>
          <%= link_to journals_edit_path(journal.id) do %><button class="fas fa-edit inline-block bg-yellow-200 hover:bg-yellow-400 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"> Edit</button><% end %>
        </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="max-w-7xl mx-auto ">
    <% if @tasks.length > 0 %>
    
          <div class=" container my-12 mx-auto px-4 md:px-12 grid grid-cols-1 sm:grid-cols-1  gap-5" >
            <div class=" rounded  text-3xl font-bold py-6 px-4 sm:px-6 lg:px-8 text-yellow-400  " style="background-image:linear-gradient(rgba(0,0,0,.6),rgba(0,0,0,.6));">
              <%=image_tag("reminder.png", alt: "Example Image" , height: "56", width: "52", class: "mb-4")%>
              Hi <%= Current.user.firstname.capitalize%> , These tasks needs your attention!!!
            </div>
          </div>
              
          <div class="container my-12 mx-auto px-4 md:px-12 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3  xl:grid-cols-3 gap-5">
            <% @tasks.each do |task|%>
              <% if task.deadline.past? || task.deadline.today? %>
                <% if !task.completed? %>
                  <div class="rounded overflow-hidden shadow-lg " style="background-image:linear-gradient(rgba(0,0,0,.6),rgba(0,0,0,.6));">
                    <div class="px-6 py-4">
                      <div style="float:right;">
                        <%= link_to journals_tasks_delete_path(task.journal_id, task.id), method: :delete, data: { confirm: "are you sure?" } do %><button class="ml-3 fas fa-times text-red-700"> </button><% end %>
                      </div>
                      <div style="float:right;">
                        <% if task.deadline.today? %>
                          <p class="text-yellow-500">Duetoday!</p>
                        <% else %>
                          <p class="text-red-500">Overdue!</p>
                        <% end %>
                      </div>
                      <div class="font-bold text-xl mb-2 text-yellow-400"><%#=task.name%> <%=task.name%></div>
                        <p class="text-gray-300 text-base mt-5"><%=task.description%></p>
                        <br>
                        <h1>Deadline <%=task.deadline.strftime("%A %b %e, %Y ")%></h1>
                      </div>
                      <div class="px-6 pt-4 pb-2 column-button">
                        <%= link_to dashboard_tasks_complete_path(task.journal_id, task.id, task.completed ? '1' : '0') do %>
                          <button class="#{task.completed ? fas fa-check : fas fa-times}  inline-block bg-green-300 hover:bg-green-400 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"> 
                            <% if task.completed %>
                              Unmark completed
                            <% else %>
                            Mark completed
                            <% end %>
                          </button>
                        <% end %>
                        <%= link_to journals_tasks_show_path(task.journal_id, task.id) do %><button class="fas fa-eye inline-block bg-blue-300 hover:bg-blue-400 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"> View </button><% end %>
                        <%= link_to journals_tasks_edit_path(task.journal_id, task.id) do %><button class="fas fa-edit inline-block bg-yellow-300 hover:bg-yellow-400 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"> Edit</button><% end %>
                      </div>
                  </div>
                <% end %>
              <% end %>
            <% end %>
        </div>
 
  <% end %>   
</div>
  

app/views/home/index.html.erb
<div class="contents">
  <section>
    <div id="about" class="font-serif">
      <h1 class="mb-10 text-4xl text-yellow-400">Journal App</h1>
      <p class="w-8/12 ">Journaling might be the most underrated activity that can boost your productivity and well-being in just a few minutes a day. Just got your thoughts down or record what happened during the day for a simple way to manage stress, enhance creativity, increase happiness, improve health, and increase work performance, according to research.</p>
        <%= link_to signin_path do %>
          <button class="fas fa-play bg-yellow-600 text-gray-100 p-4 w-full rounded tracking-wide  focus:outline-none focus:shadow-outline hover:bg-yellow-400 shadow-lg mt-10">
          Get Started </button>
        <% end %>
      <img id="drag1" src="<%= asset_path('background.jpg') %>"  width="396" height="129" class="rounded mt-10 transform duration-200 hover:scale-110 cursor-pointer">
    </div>
    </div>
    
    <div class="leaf ">
      <div><img src="http://www.pngmart.com/files/1/Fall-Autumn-Leaves-Transparent-PNG.png" height="75px" width="75px"></div>
      <div><img src="http://www.pngmart.com/files/1/Autumn-Fall-Leaves-Pictures-Collage-PNG.png" height="75px" width="75px"></div>
      <div><img src="http://www.pngmart.com/files/1/Autumn-Fall-Leaves-Clip-Art-PNG.png" height="75px" width="75px" ></div>
      <div><img src="http://www.pngmart.com/files/1/Green-Leaves-PNG-File.png" height="75px" width="75px"></div>
      <div><img src="http://www.pngmart.com/files/1/Transparent-Autumn-Leaves-Falling-PNG.png" height="75px" width="75px"></div>
      <div><img src="http://www.pngmart.com/files/1/Realistic-Autumn-Fall-Leaves-PNG.png" height="75px" width="75px"></div>
      <div><img src="http://cdn.clipart-db.ru/rastr/autumn_leaves_025.png" height="75px" width="75px"></div>
    </div>
    
    <div class="leaf leaf1">
      <div><img src="http://www.pngmart.com/files/1/Fall-Autumn-Leaves-Transparent-PNG.png" height="75px" width="75px"></div>
      <div><img src="http://www.pngmart.com/files/1/Autumn-Fall-Leaves-Pictures-Collage-PNG.png" height="75px" width="75px"></div>
      <div><img src="http://www.pngmart.com/files/1/Autumn-Fall-Leaves-Clip-Art-PNG.png" height="75px" width="75px" ></div>
      <div><img src="http://www.pngmart.com/files/1/Green-Leaves-PNG-File.png" height="75px" width="75px"></div>
      <div><img src="http://www.pngmart.com/files/1/Transparent-Autumn-Leaves-Falling-PNG.png" height="75px" width="75px"></div>
      <div><img src="http://www.pngmart.com/files/1/Realistic-Autumn-Fall-Leaves-PNG.png" height="75px" width="75px"></div>
      <div><img src="http://cdn.clipart-db.ru/rastr/autumn_leaves_025.png" height="75px" width="75px"></div>
    </div>
    
    <div class="leaf leaf2">
      <div><img src="http://www.pngmart.com/files/1/Fall-Autumn-Leaves-Transparent-PNG.png" height="75px" width="75px"></div>
      <div><img src="http://www.pngmart.com/files/1/Autumn-Fall-Leaves-Pictures-Collage-PNG.png" height="75px" width="75px"></div>
      <div><img src="http://www.pngmart.com/files/1/Autumn-Fall-Leaves-Clip-Art-PNG.png" height="75px" width="75px" ></div>
      <div><img src="http://www.pngmart.com/files/1/Green-Leaves-PNG-File.png" height="75px" width="75px"></div>
      <div><img src="http://www.pngmart.com/files/1/Transparent-Autumn-Leaves-Falling-PNG.png" height="75px" width="75px"></div>
      <div><img src="http://www.pngmart.com/files/1/Realistic-Autumn-Fall-Leaves-PNG.png" height="75px" width="75px"></div>
      <div><img src="http://cdn.clipart-db.ru/rastr/autumn_leaves_025.png" height="75px" width="75px"></div>
    </div>
  </section>
</div>

<div id="about_mobile" class="font-serif">
  <h1 class="mb-10 text-4xl text-yellow-400">Journal App</h1>
    <p class="w-8/12 mb-10 text-white">Just got your thoughts down or record what happened during the day for a simple way to manage stress, enhance creativity, increase happiness, improve health, and increase work performance, according to research.</p>
      <%= link_to signin_path do %>
        <button class="fas fa-play bg-yellow-400 text-gray-100 p-4 w-full rounded tracking-wide  focus:outline-none focus:shadow-outline hover:bg-yellow-600 shadow-lg mt-10">
        Get Started </button>
      <% end %>
    <img id="drag1" src="<%= asset_path('background.jpg') %>"  width="396" height="129" class="rounded mt-10 transform duration-200 hover:scale-110 cursor-pointer">
  </div>
</div>

app/views/home/new_task.html.erb
<div class="flex justify-center items-center " style='height:90vh; '>
  <div class="w-full max-w-lg shadow-md rounded" style="background-image:linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7))">
    <%= form_with :class => "px-8 pt-6 pb-8 mb-4", model: @task, url: tasks_new_path, locale: true do |f| %>
    <h1 class="mb-5 text-3xl text-yellow-500">Add Tasks</h1>
     <div class="mb-4">
      <%= f.label :Journal_title, :class => "block text-gray-700 text-sm font-bold mb-2" %>
      <%= collection_select :task, :journal_id, Journal.where(user_id: Current.user.id), :id, :name, { include_blank: 'Journal Title' }, { class: "input", :class => "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" } %>
     <% @task.errors.full_messages_for(:journal).each do |message| %>
        <div style="color:red;"><%= message %></div>
      <% end %>
    </div>

    <div class="mb-4">
      <%= f.label :task_title, :class => "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_field :name,  :class => "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'task Title' %>
      <% @task.errors.full_messages_for(:name).each do |message| %>
        <div style="color:red;"><%= message %></div>
      <% end %>
    </div>

    <div class="mb-6">
      <%= f.label :Description, :class => "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_area :description,  :class => "h-44 shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'Description' %>
      <% @task.errors.full_messages_for(:description).each do |message| %>
        <div style="color:red;"><%= message %></div>
      <% end %>
    </div>

    <div class="mb-6">
      <%= f.label :Deadline, :class => "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.date_field  :deadline,  :class => "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'Description' %>
      <% @task.errors.full_messages_for(:deadline).each do |message| %>
        <div style="color:red;"><%= message %></div>
      <% end %>
    </div>
     
    <div class="flex items-center justify-between">
      <%= link_to 'Back', dashboard_path, :class => "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"%>
      <%= f.submit "Save", :class => "bg-yellow-600 hover:bg-yellow-400 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer" %>
    </div>
    <% end %>
  </div>
</div>