config/routes.rb
Rails.application.routes.draw do
  
  # SIGNUP
  get '/signup', to: 'registrations#new'
  post '/signup', to: 'registrations#create'
 
  # USERS
  get '/profile', to:'users#edit_profile', as: 'profile_edit'
  patch '/profile', to:'users#update_profile', as: 'profile_update'
  get '/profile/changepassword', to:'users#edit_password', as: 'password_edit'
  patch '/profile/changepassword', to:'users#update_password', as: 'password_update'
  delete 'profile', to: 'users#delete_user', as: 'users_delete'

  # SIGNIN
  get '/signin', to: 'signin_sessions#new'
  post '/signin', to: 'signin_sessions#create'
  delete '/', to: 'signin_sessions#destroy'

  # PASSWORD RESET
  get '/password/reset', to: 'password_resets#new'
  post '/password/reset', to: 'password_resets#create'
  get '/password/reset/edit', to: 'password_resets#edit'
  patch '/password/reset/edit', to: 'password_resets#update'
  
  # HOME
  root to: 'home#index'
  get '/dashboard', to: 'home#dashboard'
  get 'tasks/new', to:'home#new_task'
  post 'tasks/new', to:'home#create_task'
  get 'dashboard/:journal_id/tasks/:task_id/:complete', to: 'home#mark_complete', as: 'dashboard_tasks_complete'

  # JOURNALS
  get '/journals/new', to: 'journals#new', as: 'journals_new'
  post '/journals/new', to: 'journals#create', as: 'journals_create'
  get '/journals/:id/edit', to: 'journals#edit', as: 'journals_edit'
  patch '/journals/:id/edit', to: 'journals#update', as: 'journals_update'
  delete '/journals/:id', to: 'journals#delete', as: 'journals_delete'

  # TASKS
  get '/journals/:id/tasks', to: 'tasks#index', as: 'journals_tasks'
  get '/journals/:id/tasks/new', to: 'tasks#new', as: 'journals_tasks_new'
  post '/journals/:id/tasks/new', to: 'tasks#create'
  get '/journals/:id/tasks/:task_id/edit', to: 'tasks#edit', as: 'journals_tasks_edit'
  patch '/journals/:id/tasks/:task_id/edit', to: 'tasks#update', as: 'journals_tasks_update'
  delete '/journals/:id/tasks/:task_id', to: 'tasks#delete', as: 'journals_tasks_delete'
  get '/journals/:id/tasks/:task_id/:complete', to: 'tasks#mark_complete', as: 'journals_tasks_complete'
  get '/journal/:id/tasks/:task_id', to: 'tasks#show', as: 'journals_tasks_show'

end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :name, uniqueness: true
  validates :name, :description, presence: true
  validates :description,  length: { minimum: 4 }
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :redirect_if_not_loggedin 

  def new
    @journal = Journal.new
  end

  def create
    @journal = Journal.new(journal_params)
    @journal.user_id = session[:user_id]

    if @journal.save
      redirect_to dashboard_path, notice: "Successfully added #{@journal.name} journal"
    else 
      render :new
    end
  end

  def edit
    @journal = Journal.find(params[:id])
  end

  def update
    @journal = Journal.find(params[:id])
    if @journal.update(journal_params)
      redirect_to dashboard_path, notice: "Successfully updated #{@journal.name} journal"
    else
      render :edit
    end
  end

  def delete
    @journal = Journal.find(params[:id])
    @journal.destroy

    redirect_to dashboard_path, notice: "Successfully deleted #{@journal.name} journal"
  end
  
  private
  
  def journal_params
    params.require(:journal).permit(:name, :description)
  end

end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/journals/edit.html.erb
<div class="flex justify-center items-center " style='height:90vh; '>
  <div class="w-full max-w-lg shadow-md rounded" style="background-image:linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7))">
    <%= form_with :class => " px-8 pt-6 pb-8 mb-4", model: @journal, url: journals_edit_path, locale: true, method: :patch do |f| %>
    <h1 class="mb-5 text-3xl text-yellow-500">Edit Journal</h1>
    <div class="mb-4">
      <%= f.label :Journal_title, :class => "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_field :name,  :class => "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'Journal Title' %>
      <% @journal.errors.full_messages_for(:name).each do |message| %>
        <div style="color:red;"><%= message %></div>
      <% end %>
    </div>
    <div class="mb-6">
      <%= f.label :Description, :class => "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_area :description,  :class => "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'Description' %>
      <% @journal.errors.full_messages_for(:description).each do |message| %>
        <div style="color:red;"><%= message %></div>
      <% end %>
    </div>
     
    <div class="flex items-center justify-between">
      <%= link_to 'Back', dashboard_path, :class => "bg-gray-500 hover:bg-gray-700 py-2 px-4 rounded focus:outline-none focus:shadow-outline"%>
      <%= f.submit "Update", :class => "bg-yellow-600 hover:bg-yellow-400 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer" %>
    </div>
    <% end %>
  </div>
</div>

app/views/journals/new.html.erb
<div class="flex justify-center items-center " style='height:90vh; '>
  <div class="w-full max-w-lg  shadow-md rounded" style="background-image:linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7))">
    <%= form_with :class => " px-8 pt-6 pb-8 mb-4", model: @journal, url: journals_new_path, locale: true do |f| %>
    <h1 class="mb-5 text-3xl text-yellow-500">Add Journal</h1>

    <div class="mb-4">
      <%= f.label :Journal_title, :class => "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_field :name,  :class => "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'Journal Title' %>
      <% @journal.errors.full_messages_for(:name).each do |message| %>
        <div style="color:red;"><%= message %></div>
      <% end %>
    </div>
    <div class="mb-6">
      <%= f.label :Description, :class => "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_area :description,  :class => "h-44 shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", :placeholder => 'Description' %>
      <% @journal.errors.full_messages_for(:description).each do |message| %>
        <div style="color:red;"><%= message %></div>
      <% end %>
    </div>
     
    <div class="flex items-center justify-between">
      <%= link_to 'Back', dashboard_path, :class => "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"%>
      <%= f.submit "Save", :class => "bg-yellow-600 hover:bg-yellow-400 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer" %>
    </div>
    <% end %>
  </div>
</div>